version: 0.2

phases:
  install:
    commands:
      - echo Installing source dependencies...
      - pip install -r requirements_for_lambda.txt -t .
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Zip the package
      - zip -r function.zip .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to Lambda
      - aws lambda update-function-code --function-name RawCircuitRun --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
