import random

def generate_instructions():
    instructions = "You are an extremely " + get_descriptor() + " " + get_profession() + ". You " + get_metaphor() + ". " + \
        get_revise_thoughts() + \
        "Your response is " + get_length() + "."
    return instructions

def get_revise_thoughts():
    revise_thoughts_list = [
        "Take some time to organize your thoughts and revise your response. ",
        "",
        ]
    return random.choice(revise_thoughts_list)

def get_descriptor():
    descriptor_list = [
        "humorous",
        "absurd",
        "affectionate",
        "aggressive",
        "aloof",
        "ambivalent",
        "angry",
        "apologetic",
        "assertive",
        "authoritative",
        "benevolent",
        "biting",
        "bold",
        "bossy",
        "calm",
        "caring",
        "casual",
        "charismatic",
        "cheeky",
        "cheerful",
        "cheery",
        "cold",
        "compassionate",
        "condescending",
        "confident",
        "conversational",
        "creepy",
        "cynical",
        "deep thinking",
        "defensive",
        "demanding",
        "desperate",
        "diligent",
        "dismissive",
        "dry",
        "eager",
        "empathetic",
        "enthusiastic",
        "evasive",
        "fatalistic",
        "formal",
        "frivolous",
        "funny",
        "grandiose",
        "grave",
        "hesitant",
        "highly opinionated",
        "humorous",
        "incredulous",
        "innovative",
        "intellectual",
        "intuitive",
        "ironic",
        "jovial",
        "lighthearted",
        "lofty",
        "manipulative",
        "melancholic",
        "meticulous",
        "mournful",
        "nostalgic",
        "offensive",
        "optimistic",
        "pessimistic",
        "petulant",
        "provocative",
        "quizzical",
        "resilient",
        "respectful",
        "reverent",
        "rude",
        "sarcastic",
        "sardonic",
        "scary",
        "slighted",
        "smug",
        "somber",
        "strict",
        "tentative",
        "uncaring",
        "urgent",
        "veiled",
        "vexed",
        "whimsical",
        "wistful",
        "zealous"
    ]
    return random.choice(descriptor_list)

def get_profession():
    get_profession_list = [
        "politician",
        "poet",
        "teacher",
        "plumber",
        "blacksmith",
        "auctioneer",
        "camp counselor",
        "cowboy",
        "farmer",
        "woodworker",
        "youtuber",
        "degnerate gambler",
        "college professor",
        "lazy bum",
        "young child",
        "conversationalist",
        "environmental activist",
        "social worker",
        "veterinarian",
        "chef",
        "journalist",
        "software engineer",
        "artist",
        "human rights lawyer",
        "nurse",
        "musician",
        "architect",
        "biologist",
        "civil rights activist",
        "economist",
        "fashion designer",
        "graphic designer",
        "historian",
        "industrial designer",
        "librarian",
        "mathematician",
        "nutritionist",
        "pharmacist",
        "physicist",
        "psychologist",
        "religious leader",
        "school principal",
        "social media influencer",
        "urban planner",
        "veterinarian technician",
        "wildlife conservationist",
        "athlete",
        "baker",
        "carpenter",
        "dentist",
        "electrical engineer",
        "filmmaker",
        "gardener",
        "human resources manager",
        "interpreter",
        "judge",
        "kindergarten teacher",
        "mechanic",
        "nurse practitioner",
        "optometrist",
        "physiotherapist",
        "quality assurance analyst",
        "research scientist",
        "sailor",
        "translator",
        "video game developer"
    ]
    return random.choice(get_profession_list)

def get_metaphor():
    metaphor_list = [
        "use subtle metaphor",
        "use pompous words and pretentious phrases",
        "use slang",
        "use concise, factual statements",
        "express empathy and understanding",
        "incorporate humor and witty remarks",
        "offer constructive criticism and thoughtful advice",
        "use passionate and emotive language",
        "respond with a question",
        "use a metaphor to make your point",
        "respond as if you were speaking to a child",
        "respond as if you were speaking to a highly educated adult",
        ]
    return random.choice(metaphor_list)

def get_length():
    length_list = [
        "one sentence",
        "one short sentence",
        "one long sentence",
        "a few sentences",
        "a few short sentences",
        "a few long sentences",
        "one paragraph",
        "one short paragraph",
        "one long paragraph",
        "short witty poems",
        "a tweet",
        "a facebook post",
        "a reddit post",
    ]
    return random.choice(length_list)
