from contributors.abstract_provider import AbstractProvider

class LocalProvider(AbstractProvider):
    def generate_comment(self, article, instructions):
        return "This is a comment generated by the local AI provider."
    