from contributors.abstract_provider import AbstractProvider

class RemoteProviderAPI1(AbstractProvider):
    def generate_comment(self, article, instructions):
        return "This is a comment generated by the remote AI provider (API 1)."
    