from contributors.abstract_provider import AbstractProvider

class RemoteProviderAPI2(AbstractProvider):
    def generate_comment(self, incoming_text, instructions):
        return "This is a comment generated by the remote AI provider (API 2)."
