from contributors.abstract_provider import AbstractProvider

class RemoteProviderAPI2(AbstractProvider):
    def generate_comment(self, user_content, system_content):
        return "This is a comment generated by the remote AI provider (API 2)."
